---
dist: trusty
language: python
sudo: false

env:
  - ansible_remote_user: ubuntu
  - ansible_remote_user: root

install:
  # Install latest ansible from pip
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
