---
- name: Install Debian build dependencies
  package:
    name: binutils
    state: present
  become: yes

- include_tasks: download-source.yml

- name: build deb package
  shell: ./build-deb.sh
  args:
    chdir: "{{ efs_utils_source_dir }}"
    creates: build/amazon-efs-utils*deb

- name: install deb package
  shell: apt -y install ./build/amazon-efs-utils*deb
  args:
    chdir: "{{ efs_utils_source_dir }}"
  become: yes
  register: efs_utils_pkg_install
  changed_when: '"Unpacking amazon-efs-utils" in efs_utils_pkg_install.stdout'
